# Generated by Django 5.0.2 on 2024-09-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades_disponibles', models.IntegerField()),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
