# Generated by Django 5.0.2 on 2024-09-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_telefono_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='OppoPhone',
            fields=[
                ('telefono_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.telefono')),
                ('carga_rapida', models.BooleanField(default=False)),
            ],
            bases=('api.telefono',),
        ),
        migrations.CreateModel(
            name='SamsungPhone',
            fields=[
                ('telefono_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.telefono')),
                ('tecnologia_5g', models.BooleanField(default=False)),
            ],
            bases=('api.telefono',),
        ),
        migrations.CreateModel(
            name='XiaomiPhone',
            fields=[
                ('telefono_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.telefono')),
                ('version_miui', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('api.telefono',),
        ),
    ]
