# Generated by Django 5.0.2 on 2024-09-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_oppophone_samsungphone_xiaomiphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='IphonePhone',
            fields=[
                ('telefono_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.telefono')),
                ('bateria', models.BooleanField(default=False)),
            ],
            bases=('api.telefono',),
        ),
    ]
